# Generated by Django 3.0.2 on 2020-02-01 12:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Уникальный ключ')),
                ('full_name', models.TextField(verbose_name='Имя автора')),
                ('birth_year', models.SmallIntegerField(verbose_name='Год рожения')),
                ('country', models.CharField(max_length=2, verbose_name='Страна')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Уникальный ключ')),
                ('ISBN', models.CharField(max_length=13, verbose_name='Международный стандартный книжный номер')),
                ('title', models.TextField(verbose_name='Название')),
                ('description', models.TextField(verbose_name='Аннотация')),
                ('year_release', models.SmallIntegerField(verbose_name='Год издания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_author', to='bookclub.Author', verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='BookReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion', models.NullBooleanField(default=None, verbose_name='Чтение завершено')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookreading_book', to='bookclub.Book', verbose_name='Книга')),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Уникальный ключ')),
                ('name', models.CharField(max_length=256, verbose_name='Имя')),
                ('books', models.ManyToManyField(through='bookclub.BookReading', to='bookclub.Book', verbose_name='Книги')),
            ],
        ),
        migrations.AddField(
            model_name='bookreading',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookreading_reader', to='bookclub.Reader', verbose_name='Читатель'),
        ),
    ]
