# Generated by Django 3.0.2 on 2020-02-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='copy_count',
            field=models.SmallIntegerField(default=1, verbose_name='Число копий'),
            preserve_default=False,
        ),
    ]
